// Generated by `pnpm dist:metadata` from package.json.
// Do not edit this file directly.

/**
 * Package-owned distribution metadata, stamped into the source so a bundled executable carries
 * the release identity as ordinary code. Production workflow project preparation derives the
 * `.kimchi/workflows/package.json` contract exclusively from this object.
 */
export interface DistributionMetadata {
	readonly name: string
	readonly version: string
	readonly packageManager: string
	readonly toolchain: {
		readonly piCodingAgent: string
		readonly piTui: string
		readonly typebox: string
		readonly typesNode: string
		readonly typescript: string
		readonly vitest: string
	}
}

export const distribution: DistributionMetadata = {
	name: "@kimchi-dev/kimchi-workflows",
	version: "0.0.0",
	packageManager: "pnpm@10.33.0",
	toolchain: {
		piCodingAgent: "0.84.1",
		piTui: "0.84.1",
		typebox: "1.3.7",
		typesNode: "^26.2.0",
		typescript: "^7.0.2",
		vitest: "4.1.10",
	},
}
